option(USE_BUILTIN_MINIZIP "Use builtin minizip library" YES)
macro(libminizip target)
  if(USE_BUILTIN_MINIZIP)
    add_subdirectory(../zip build_zip)
    get_directory_property(MINIZIP_INCLUDE_DIRS DIRECTORY ../zip DEFINITION MINIZIP_INCLUDE_DIRS)
    get_directory_property(MINIZIP_LIBRARIES DIRECTORY ../zip DEFINITION MINIZIP_LIBRARIES)
  else()
    find_package(PkgConfig)
    pkg_check_modules(MINIZIP minizip)
  endif()

  MESSAGE(STATUS "MINIZIP library found at: ${MINIZIP_LIBRARIES}")
  MESSAGE(STATUS "MINIZIP includes found at: ${MINIZIP_INCLUDE_DIRS}")
  target_include_directories(${target} PRIVATE ${MINIZIP_INCLUDE_DIRS})
  target_link_libraries(${target} ${MINIZIP_LIBRARIES})
  libzlib(${target}) # needed for crc32
endmacro()

option(USE_BUILTIN_ZLIB "Use builtin zlib library" NO)
macro(libzlib target)
  if(USE_BUILTIN_ZLIB)
    # internal zlib not enabled for Domoticz app either, so we don't care
    message(FATAL_ERROR "builtin zlib not supported yet")
    #add_subdirectory(../zlib build_zlib)
    #get_directory_property(ZLIB_INCLUDE_DIRS DIRECTORY ../zlib DEFINITION ZLIB_INCLUDE_DIRS)
    #get_directory_property(ZLIB_LIBRARIES DIRECTORY ../zlib DEFINITION ZLIB_LIBRARIES)
  else()
    find_package(ZLIB REQUIRED)
  endif()

  if(ZLIB_FOUND)
    MESSAGE(STATUS "ZLIB library found at: ${ZLIB_LIBRARIES}")
    MESSAGE(STATUS "ZLIB includes found at: ${ZLIB_INCLUDE_DIRS}")
    target_include_directories(${target} PRIVATE ${ZLIB_INCLUDE_DIRS})
    target_link_libraries(${target} ${ZLIB_LIBRARIES})
  else()
    MESSAGE(FATAL_ERROR "ZLIB not found on your system, try to get this installed. (for example 'sudo apt-get install zlib1g-dev')")
  endif()
endmacro()
