option(USE_BUILTIN_SQLITE "Use builtin sqlite library" NO)
macro(libsqlite target)
if(USE_BUILTIN_SQLITE)
  add_subdirectory (../sqlite build_sqlite3)
  get_directory_property (SQLite_LIBRARIES DIRECTORY ../sqlite DEFINITION SQLite_LIBRARIES)
  get_directory_property (SQLite_INCLUDE_DIRS DIRECTORY ../sqlite DEFINITION SQLite_INCLUDE_DIRS)
  target_link_libraries(${target} ${SQLite_LIBRARIES})
else()
  find_package(SQLite3 REQUIRED)
  target_include_directories(${target} PRIVATE ${SQLite3_INCLUDE_DIRS})
  MESSAGE(STATUS "SQLite3 libs : ${SQLite3_LIBRARIES}")
  target_link_libraries(${target} SQLite::SQLite3)
  add_definitions(-DWITH_EXTERNAL_SQLITE)
endif()
endmacro()
