#!/bin/bash
# GitHub Issue Creation Script
# This script helps create the Angular migration GitHub issue

echo "=========================================="
echo "GitHub Issue Creation for Angular Migration"
echo "=========================================="
echo ""
echo "STEP 1: Navigate to GitHub"
echo "  1. Open: https://github.com/domoticz/domoticz/issues"
echo "  2. Click 'New issue' button"
echo ""
echo "STEP 2: Copy Issue Content"
echo "  The issue content is in: NEW_GITHUB_ISSUE.md"
echo "  You can copy it with:"
echo "    cat NEW_GITHUB_ISSUE.md | pbcopy  # macOS"
echo "    cat NEW_GITHUB_ISSUE.md | xclip   # Linux"
echo ""
echo "STEP 3: Paste and Configure"
echo "  1. Paste content into issue description"
echo "  2. Set title: '[EPIC] Migrate jQuery-based Pages to Angular Architecture'"
echo "  3. Add labels:"
echo "     - enhancement"
echo "     - angular"
echo "     - refactor"
echo "     - frontend"
echo "     - epic"
echo "  4. Assign to appropriate milestone/project"
echo ""
echo "STEP 4: Link Related Items"
echo "  - Link to current PR (filtering fixes)"
echo "  - Link to original flash bug issue"
echo "  - Link to Temperature/Weather implementation"
echo ""
echo "Issue content preview:"
echo "----------------------------------------"
head -20 NEW_GITHUB_ISSUE.md
echo "..."
echo "----------------------------------------"
echo ""
echo "Total issue size: $(wc -l < NEW_GITHUB_ISSUE.md) lines"
echo ""
echo "Ready to create issue? Follow steps above!"
