#!/usr/bin/env python3
"""
Angular Migration Helper Script

This script provides utilities to assist with migrating jQuery-based
pages to Angular architecture.

Usage:
    python3 migration_helper.py analyze <controller_file>
    python3 migration_helper.py generate-widget <widget_name>
    python3 migration_helper.py stats
"""

import sys
import os
import re
from pathlib import Path


def analyze_controller(filepath):
    """Analyze a jQuery-based controller for migration complexity."""
    
    print(f"\n{'='*60}")
    print(f"Analyzing: {filepath}")
    print(f"{'='*60}\n")
    
    with open(filepath, 'r') as f:
        content = f.read()
    
    # Count various complexity indicators
    stats = {
        'total_lines': len(content.split('\n')),
        'html_calls': len(re.findall(r'\.html\(', content)),
        'append_calls': len(re.findall(r'\.append\(', content)),
        'jquery_selectors': len(re.findall(r'\$\(["\']#', content)),
        'string_concat': len(re.findall(r'\+\s*["\']<', content)),
        'mobile_checks': len(re.findall(r'ismobile|DashboardType.*2', content, re.I)),
        'setTimeout_calls': len(re.findall(r'setTimeout', content)),
    }
    
    # Print statistics
    print("Complexity Metrics:")
    print(f"  Total Lines: {stats['total_lines']}")
    print(f"  .html() calls: {stats['html_calls']}")
    print(f"  .append() calls: {stats['append_calls']}")
    print(f"  jQuery selectors: {stats['jquery_selectors']}")
    print(f"  String concatenations: {stats['string_concat']}")
    print(f"  Mobile/desktop checks: {stats['mobile_checks']}")
    print(f"  setTimeout calls: {stats['setTimeout_calls']}")
    
    # Calculate migration difficulty
    complexity_score = (
        stats['html_calls'] * 2 +
        stats['string_concat'] * 1 +
        stats['mobile_checks'] * 3 +
        stats['jquery_selectors'] * 0.5
    )
    
    print(f"\nMigration Complexity Score: {complexity_score:.0f}")
    
    if complexity_score < 100:
        difficulty = "Low"
    elif complexity_score < 300:
        difficulty = "Medium"
    elif complexity_score < 600:
        difficulty = "High"
    else:
        difficulty = "Very High"
    
    print(f"Estimated Difficulty: {difficulty}")
    
    # Provide recommendations
    print("\nRecommendations:")
    if stats['mobile_checks'] > 5:
        print("  - Consider separating mobile and desktop implementations")
    if stats['html_calls'] > 50:
        print("  - High number of DOM manipulations - create reusable components")
    if stats['string_concat'] > 100:
        print("  - Extensive HTML generation - use Angular templates")
    if stats['setTimeout_calls'] > 0:
        print("  - Remove setTimeout workarounds when using Angular")
    
    return stats


def generate_widget_skeleton(widget_name):
    """Generate a skeleton Angular widget directive."""
    
    print(f"\nGenerating widget skeleton for: {widget_name}")
    
    # Create directive file
    directive_content = f"""/**
 * {widget_name} Widget Directive
 * 
 * Generated by migration helper script
 */

define(['app'], function (app) {{
    'use strict';

    app.directive('dz{widget_name}Widget', function() {{
        return {{
            restrict: 'E',
            scope: {{
                item: '=',
                config: '='
            }},
            templateUrl: 'views/widgets/{widget_name.lower()}_widget.html',
            controller: '{widget_name}WidgetController',
            controllerAs: 'ctrl'
        }};
    }});

    app.controller('{widget_name}WidgetController', ['$scope', 'deviceApi',
        function($scope, deviceApi) {{
        
        var ctrl = this;
        var item = $scope.item;
        
        // Add your controller logic here
        
        ctrl.getStatusText = function() {{
            return item.Status || 'Unknown';
        }};
        
        ctrl.toggleDevice = function() {{
            var newStatus = item.Status === 'On' ? 'Off' : 'On';
            deviceApi.switchDevice(item.idx, newStatus);
        }};
    }}]);
}});
"""
    
    # Create template file
    template_content = f"""<!-- {widget_name} Widget Template -->
<div class="item" ng-class="ctrl.getBackgroundClass()">
    <section>
        <table border="0" cellpadding="0" cellspacing="0">
            <tr>
                <td id="name">{{{{item.Name}}}}</td>
                <td id="status">{{{{ctrl.getStatusText()}}}}</td>
                <td id="lastupdate">{{{{item.LastUpdate}}}}</td>
            </tr>
        </table>
    </section>
</div>
"""
    
    # Write files
    widgets_dir = Path('www/app/widgets')
    widgets_dir.mkdir(parents=True, exist_ok=True)
    
    directive_file = widgets_dir / f'{widget_name.lower()}Widget.js'
    with open(directive_file, 'w') as f:
        f.write(directive_content)
    
    templates_dir = Path('www/views/widgets')
    templates_dir.mkdir(parents=True, exist_ok=True)
    
    template_file = templates_dir / f'{widget_name.lower()}_widget.html'
    with open(template_file, 'w') as f:
        f.write(template_content)
    
    print(f"  Created: {directive_file}")
    print(f"  Created: {template_file}")
    print("\nNext steps:")
    print(f"  1. Edit {directive_file} to add widget logic")
    print(f"  2. Edit {template_file} to customize template")
    print(f"  3. Add widget to your page controller")


def show_migration_stats():
    """Show overall migration statistics."""
    
    print("\n" + "="*60)
    print("Angular Migration Statistics")
    print("="*60 + "\n")
    
    # Controllers to analyze
    controllers = [
        'www/app/LightsController.js',
        'www/app/ScenesController.js',
        'www/app/UtilityController.js',
        'www/app/DashboardController.js'
    ]
    
    total_stats = {
        'total_lines': 0,
        'html_calls': 0,
        'controllers': 0
    }
    
    for controller in controllers:
        if os.path.exists(controller):
            with open(controller, 'r') as f:
                content = f.read()
            
            lines = len(content.split('\n'))
            html_calls = len(re.findall(r'\.html\(', content))
            
            print(f"{os.path.basename(controller):30} {lines:6} lines  {html_calls:3} .html() calls")
            
            total_stats['total_lines'] += lines
            total_stats['html_calls'] += html_calls
            total_stats['controllers'] += 1
    
    print("\n" + "-"*60)
    print(f"{'TOTAL':30} {total_stats['total_lines']:6} lines  {total_stats['html_calls']:3} .html() calls")
    print("-"*60)
    
    expected_reduction = 0.79  # 79% reduction based on plan
    expected_final = int(total_stats['total_lines'] * (1 - expected_reduction))
    reduction_lines = total_stats['total_lines'] - expected_final
    
    print(f"\nExpected after migration: ~{expected_final} lines")
    print(f"Code reduction: ~{reduction_lines} lines ({expected_reduction*100:.0f}%)")
    print(f"jQuery .html() calls to remove: {total_stats['html_calls']}")


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    
    command = sys.argv[1]
    
    if command == 'analyze':
        if len(sys.argv) < 3:
            print("Usage: migration_helper.py analyze <controller_file>")
            sys.exit(1)
        analyze_controller(sys.argv[2])
    
    elif command == 'generate-widget':
        if len(sys.argv) < 3:
            print("Usage: migration_helper.py generate-widget <widget_name>")
            sys.exit(1)
        generate_widget_skeleton(sys.argv[2])
    
    elif command == 'stats':
        show_migration_stats()
    
    else:
        print(f"Unknown command: {command}")
        print(__doc__)
        sys.exit(1)


if __name__ == '__main__':
    main()
