#!/usr/bin/env bash

# This script can be used to upgrade to the latest beta version

set -e

lowercase(){
    echo "$1" | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/"
}

OS=`lowercase \`uname -s\``
MACH=`uname -m`
if [ ${MACH} = "armv6l" ]
then
 MACH="armv7l"
fi

# Must be root to install

if [[ $EUID -eq 0 ]]; then
	echo "You are root."
else
	echo "Root access is required, please run this script with sudo"
	exit 1
fi
echo "Stopping Domoticz and creating backup of current install..."
base=$(basename $PWD)
timestamp=$(date +%Y%m%d_%H%M%S)
# remove old backup
rm -f $base.backup*.tar.gz
cd ..
# create backup in parent folder (mostly home)
sudo service domoticz.sh stop
tar --exclude $base/backups -czf $base.backup_$timestamp.tar.gz $base
# move backup to domoticz folder
mv $base.backup_$timestamp.tar.gz $base/$base.backup_$timestamp.tar.gz
echo "Backup finished..."
cd $base
echo "Downloading latest beta version..."
wget -4 -O domoticz_beta.tgz --no-check-certificate "https://www.domoticz.com/download.php?channel=beta&type=release&system=${OS}&machine=${MACH}"
if [ $? -ne 0 ]
then
 echo "Problem downloading new Domoticz version!!. Stopping and restarting current version..."
 sudo service domoticz.sh start
 exit 1
fi
echo "Checking file integrity..."
tar -tzf domoticz_beta.tgz >/dev/null
if [ $? -ne 0 ]
then
 echo "Problem in downloaded Domoticz archive!!. Stopping and restarting current version..."
 sudo service domoticz.sh start
 exit 1
fi
echo "Installing new version..."
tar xvfz domoticz_beta.tgz
rm domoticz_beta.tgz
echo "Starting Domoticz... (please standby...)"
sudo service domoticz.sh start
echo "Done..."
