#!/bin/sh

# This script can be used to upgrade to the latest release version

lowercase(){
    echo "$1" | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/"
}

OS=`lowercase \`uname -s\``
MACH=`uname -m`
if [ ${MACH} = "armv6l" ]
then
 MACH="armv7l"
fi

echo "Updating to latest release version..."
echo "Please Standby..."
wget -O domoticz_release.tgz --no-check-certificate "https://www.domoticz.com/download.php?channel=stable&type=release&system=${OS}&machine=${MACH}"
tar xvfz domoticz_release.tgz
rm domoticz_release.tgz
echo "Restarting Domoticz... (please standby...)"
sudo service domoticz.sh restart
