all: configure Makefile.in
	# Now you may proceed with ./configure and make

Makefile.in: Makefile.am configure.in aclocal.m4
	automake --add-missing

configure: aclocal.m4
	autoconf

aclocal.m4:
	aclocal

clean:
	rm -f aclocal.m4
	rm -f configure
	rm -rf autom4te.cache
	rm -f Makefile.in
	rm -f depcomp install-sh missing