export const DomoticzBlocklyMsg = {

  // Control Blocks.
  DOMOTICZCONTROLS_IF_TOOLTIP: 'If statements about one or more devices or time schedules are true, then do some actions (set Lamp = "On").',

  // Logic Blocks.
  LANG_LOGIC_COMPARE_TOOLTIP_EQ: 'Return true if both inputs equal each other.',
  LANG_LOGIC_COMPARE_TOOLTIP_NEQ: 'Return true if both inputs are not equal to each other.',
  LANG_LOGIC_COMPARE_TOOLTIP_LT: 'Return true if the first input is smaller\nthan the second input.',
  LANG_LOGIC_COMPARE_TOOLTIP_LTE: 'Return true if the first input is smaller\nthan or equal to the second input.',
  LANG_LOGIC_COMPARE_TOOLTIP_GT: 'Return true if the first input is greater\nthan the second input.',
  LANG_LOGIC_COMPARE_TOOLTIP_GTE: 'Return true if the first input is greater\nthan or equal to the second input.',
  LANG_LOGIC_OPERATION_TOOLTIP_AND: 'Return true if both inputs are true.',
  LANG_LOGIC_OPERATION_TOOLTIP_OR: 'Return true if either inputs are true.',
  LANG_LOGIC_NEGATE_INPUT_NOT: 'not',
  LANG_LOGIC_NEGATE_TOOLTIP: 'Returns true if the input is false.\nReturns false if the input is true.',
  LANG_LOGIC_BOOLEAN_TOOLTIP: 'Returns either true or false.',
  DOMOTICZSWITCHES_TOOLTIP: 'A list of switchable devices. Can be used in an IF statement to check current state, or in a "Set" block in a DO statement to change the state.',
  DOMOTICZUSERVARIABLES_TOOLTIP: 'A list of user defined variables. Can be used in an IF statement to check current value, or in a "Set" block in a DO statement to change the value.',
  DOMOTICZVARIABLES_TEMPERATURE_TOOLTIP: 'This is a temperature measurement device. Use it in an IF statement to check valid temperature values,\ni.e. "if Bathroom temperature > 20". Cannot be used in Set blocks.',
  DOMOTICZVARIABLES_HUMIDITY_TOOLTIP: 'This is a humidity measurement device. Use it in an IF statement to check valid humidity values, i.e. "if Bathroom humidity > 50". The percentage sign is omitted. Cannot be used in Set blocks.',
  DOMOTICZVARIABLES_DEWPOINT_TOOLTIP: 'This is a dewpoint measurement device. Use it in an IF statement to check valid temperature values,\ni.e. "if Bathroom temperature > 20". Cannot be used in Set blocks.',
  DOMOTICZVARIABLES_BAROMETER_TOOLTIP: 'This is a barometer measurement device. Use it in an IF statement to check valid barometer values,\ni.e. "if Outside barometer > 1020". Cannot be used in Set blocks.',
  DOMOTICZVARIABLES_WEATHER_TOOLTIP: 'This is a weather measurement device. Use it in an IF statement to check valid values. Cannot be used in Set blocks.',
  DOMOTICZVARIABLES_UTILITY_TOOLTIP: 'This is a utility measurement device. Use it in an IF statement to check valid utility values,\ni.e. "if EnergyMeter value > 2000". Cannot be used in Set blocks.',
  DOMOTICZVARIABLES_TEXT_TOOLTIP: 'Use this block in a "Do" statement to change the value of a text device.',
  DOMOTICZVARIABLES_SCENES_TOOLTIP: ' Scenes can only be used in a Do statement (i.e cannot be checked for a status).',
  DOMOTICZVARIABLES_GROUPS_TOOLTIP: ' Groups can only be used in a Do statement (i.e cannot be checked for a status).',
  DOMOTICZ_LOGIC_SET_TOOLTIP: 'Use this block in a "Do" statement to change the state of a designated device.',
  DOMOTICZ_LOGIC_SETAFTER_TOOLTIP: 'Use this block in a "Do" statement to change the state of a designated device after a specified number of seconds.\n E.g. if you want to switch a lamp after 10 seconds.',
  DOMOTICZ_LOGIC_SETDELAYED_TOOLTIP: 'Use this block in a "Do" statement to change the state of a designated device for a specified number of minutes.\n E.g. if you want to switch a lamp on for only 10 minutes.',
  DOMOTICZ_LOGIC_SETRANDOM_TOOLTIP: 'Use this block in a "Do" statement to change the state of a designated device randomly within a specified timeframe.\n E.g. switch on a lamp somewhere in the next 30 minutes.',
  DOMOTICZ_LOGIC_SETLEVEL_TOOLTIP: 'Use this block in a "Do" statement to change the dim level of a designated dimmable device.\n Input value must be a percentage, i.e. 0-100.',
  DOMOTICZ_LOGIC_TIMEVALUE_TOOLTIP: 'Enter a valid time in 24 hour format, e.g. 23:59',
  DOMOTICZ_LOGIC_WEEKDAY_TOOLTIP: 'Use this block in an IF statement to check the day of the week.',
  DOMOTICZ_LOGIC_SUNRISESUNSET_TOOLTIP: 'Use this block to check against sunrise/sunset time as specified in the Domoticz preferences.',
  DOMOTICZ_LOGIC_NOTIFICATION_TOOLTIP: 'Use this block in a DO statement to send a notification based on the IF statement. Use text blocks from this group to specify subject and message.\nDepending on the preferences setting the message will go to either email or notification service or both.',
  DOMOTICZ_LOGIC_EMAIL_TOOLTIP: 'Use this block in a DO statement to send a email based on the IF statement. Use text blocks from this group to specify subject, message and to fields.',
  DOMOTICZ_LOGIC_SMS_TOOLTIP: 'Use this block in a DO statement to send a SMS based on the IF statement. Use text blocks from this group to specify subject field.',
  DOMOTICZ_LOGIC_IFTTT_TOOLTIP: 'Use this block in a DO statement to trigger a IFTTT Maker/Webhook event. Use text blocks from this group to specify EventName and optional values.',
  DOMOTICZ_LOGIC_SCRIPT_TOOLTIP: 'Use this block in a DO statement to start a script. (/home/user/myscript.sh)',
  DOMOTICZ_LOGIC_NOTIFICATION_PRIORITY_TOOLTIP: 'Use this block in a DO statement to set the priority of a notificatio.',
  DOMOTICZ_SECURITY_STATUS_TOOLTIP: 'The current state of the Domoticz security system. Can only be checked, not set through an event.',
  DOMOTICZ_LOGIC_OPENURL_TOOLTIP: 'Enter a url to open. This does not actually retrieve anything from the url, use it to trigger an external api.',
  DOMOTICZ_LOGIC_URL_TEXT_TOOLTIP: 'Enter a valid url without the "http://" prefix.',
  DOMOTICZ_LOGIC_WRITETOLOG_TOOLTIP: 'Use this block with a text, uservariable or device block to write a text or value into the Domoticz log.',
  DOMOTICZ_LOGIC_CAMERA_TOOLTIP: 'Use this block in a "Do" statement to send a Camera snapshot after a specified number of seconds.\n E.g. if you want to send a snapshot after 10 seconds.',
  DOMOTICZ_LOGIC_SETPOINT_TOOLTIP: 'Use this block in a "Do" statement to set a Setpoint value.',
  DOMOTICZVARIABLES_ZWAVEALARMS_TOOLTIP: 'This is a ZWave Alarm Type device. Use it in an IF statement to check its value,\ni.e. "if Burglar Alarm (0x07) value == 1". Cannot be used in Set blocks.',
  DOMOTICZCONTROLS_MSG_IF: 'If',
  DOMOTICZCONTROLS_MSG_ELSEIF: 'Else if',
  DOMOTICZCONTROLS_MSG_DO: 'Do',
  DOMOTICZCONTROLS_MSG_TEMP: 'temp.',
  DOMOTICZCONTROLS_MSG_HUM: 'hum.',
  DOMOTICZCONTROLS_MSG_DEWPOINT: 'dew.',
  DOMOTICZCONTROLS_MSG_BARO: 'baro.',
  DOMOTICZCONTROLS_MSG_UTILITY: 'actual.',
  DOMOTICZCONTROLS_MSG_TEXT: 'text.',
  DOMOTICZCONTROLS_MSG_SET: 'Set ',
  DOMOTICZCONTROLS_MSG_SEND: 'Send ',
  DOMOTICZCONTROLS_MSG_TO: 'To ',
  DOMOTICZCONTROLS_MSG_FOR: 'For ',
  DOMOTICZCONTROLS_MSG_AFTER: 'After ',
  DOMOTICZCONTROLS_MSG_SECONDS: 'seconds',
  DOMOTICZCONTROLS_MSG_MINUTES: 'minutes',
  DOMOTICZCONTROLS_MSG_RANDOM: 'Random within',
  DOMOTICZCONTROLS_MSG_SETLEVEL: 'Level (%)',
  DOMOTICZCONTROLS_MSG_TIME: 'Time',
  DOMOTICZCONTROLS_MSG_DAY: 'Day ',
  DOMOTICZCONTROLS_MSG_SECURITY: 'Security status',
  DOMOTICZCONTROLS_MSG_GROUP: 'group',
  DOMOTICZCONTROLS_MSG_SCENE: 'scene',
  DOMOTICZCONTROLS_MSG_SENDCAMERA: 'Send camera snapshot',
  DOMOTICZCONTROLS_MSG_SETSETPOINT: 'Set SetPoint',
  DOMOTICZCONTROLS_MSG_WITHSUBJECT: 'with subject',
  DOMOTICZCONTROLS_MSG_DEGREES: 'Degrees',
  DOMOTICZCONTROLS_MSG_ZWAVEALARMS: 'Value',

}
