return
{
	["result"]= {
		{
			['idx'] = '1',
			['Description'] = 'Description 1',
			['BatteryLevel'] = 10,
			['SignalLevel'] = '10',
			['SubType'] = 'Zone',
			['Type'] = 'Heating',
			['HardwareName'] = 'hw1',
			['HardwareType'] = 'ht1',
			['HardwareID'] = 1,
			['HardwareTypeVal'] = 1,
			['HaveTimeout'] = true,
			['SwitchType'] = 'Contact',
			['SwitchTypeVal'] = 2,
			['Name'] = 'Name1',
			['Data'] = 'On',
			['Status'] = 'On'
		},
		{
			['idx'] = '2',
			['Description'] = 'Description 2',
			['BatteryLevel'] = 20,
			['SignalLevel'] = '20',
			['SubType'] = 'Lux',
			['Type'] = 'Lux',
			['HardwareName'] = 'hw2',
			['HardwareType'] = 'ht2',
			['HardwareID'] = 2,
			['HardwareTypeVal'] = 2,
			['HaveTimeout'] = false,
			['SwitchType'] = "Motion Sensor",
			['SwitchTypeVal'] = 8,
			['Name'] = 'Name2',
			['Data'] = '1;2;3'
		},
		{
			['idx'] = '3',
			['Description'] = 'Description 3',
			['BatteryLevel'] = 30,
			['SignalLevel'] = '30',
			['SubType'] = 'Energy',
			['Type'] = 'P1 Smart Meter',
			['HardwareName'] = 'hw3',
			['HardwareType'] = 'ht3',
			['HardwareID'] = 3,
			['HaveTimeout'] = false,
			['HardwareTypeVal'] = 3,
			['SwitchType'] = 'On/Off',
			['SwitchTypeVal'] = 0,
			['Name'] = 'Name3',
			['Data'] = 'On',
			['Status'] = 'On'
		},
		{
			['idx'] = '4',
			['Description'] = 'Description 4',
			['BatteryLevel'] = 40,
			['SignalLevel'] = '-',
			['SubType'] = 'SetPoint',
			['Type'] = 'Thermostat',
			['HardwareName'] = 'hw4',
			['HardwareType'] = 'ht4',
			['HardwareID'] = 4,
			['HardwareTypeVal'] = 4,
			['HaveTimeout'] = false,
			['SwitchType'] = 'Security',
			['SwitchTypeVal'] = 0,
			['Name'] = 'Name4',
			['Data'] = 'On'
		},
		{
			['idx'] = '5',
			['Description'] = 'Description 5',
			['BatteryLevel'] = 40,
			['SignalLevel'] = '-',
			['SubType'] = 'kWh',
			['Type'] = 'General',
			['HardwareName'] = 'hw4',
			['HardwareType'] = 'ht4',
			['HardwareID'] = 4,
			['HardwareTypeVal'] = 4,
			['HaveTimeout'] = false,
			['SwitchType'] = 'Security',
			['SwitchTypeVal'] = 0,
			['CounterToday'] = '1.234 kWh',
			['Counter'] = '567 kWh',
			['Name'] = 'Name5',
			['Data'] = '3;3;3;3',
			['Level'] = 10
		},
		{
			['idx'] = '7',
			['Description'] = 'Description 6',
			['BatteryLevel'] = 40,
			['SignalLevel'] = '-',
			['SubType'] = 'Electric',
			['Type'] = 'Usage',
			['HardwareName'] = 'hw4',
			['HardwareType'] = 'ht4',
			['HardwareID'] = 4,
			['HardwareTypeVal'] = 4,
			['HaveTimeout'] = false,
			['Name'] = 'Name5',
			['Data'] = '16.5 Wat',
		},
		{
			["Data"] = 'On',
			['Description'] = 'Descr Scene 1',
			["LastUpdate"]= "2016-01-29 15:45:52",
			["Name"]= "Scene1",
			["Status"]= "On",
			["Type"]= "Scene",
			["TypeImg"]= "scene",
			["idx"]= "1"
		},
		{
			["Data"] = 'Off',
			['Description'] = 'Descr Scene 2',
			["LastUpdate"]= "2016-01-29 15:45:52",
			["Name"]= "Scene2",
			["Status"]= "On",
			["Type"]= "Scene",
			["TypeImg"]= "scene",
			["idx"]= "2"
		},
		{
			["Data"]= "Mixed",
			['Description'] = 'Descr Scene 3',
			["LastUpdate"]= "2016-04-09 23:17:21",
			["Name"]= "Group1",
			["Status"]= "Mixed",
			["Type"]= "Group",
			["idx"]= "3"
		},
		{
			["Data"]= "On",
			['Description'] = 'Descr Scene 4',
			["LastUpdate"]= "2016-04-09 23:17:21",
			["Name"]= "Group2",
			["Status"]= "On",
			["Type"]= "Group",
			["idx"]= "4"
		},
		{
			["Data"]= "Blah",
			['Description'] = 'Description 6',
			["LastUpdate"]= "2016-04-09 23:17:21",
			["Name"]= "Text1",
			["Status"]= "Blah",
			['HaveTimeout'] = false,
			["Type"]= "General",
			["SubType"]= "Text",
			["idx"]= "6"
		},
	}
}
