#!/bin/sh
cd $1
tar xfz update.tgz
rm update.tgz

sudo service domoticz.sh stop
systemctl stop domoticz.service
echo "please standby... (waiting 15 seconds)"
sleep 15
sudo service domoticz.sh start
systemctl start domoticz.service
