name: PR Check (Unix)

concurrency:
  group: linux-pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - development
      - master
    paths-ignore:
      - 'msbuild/**'
      - '.github/**'
      - 'tools/**'
      - '**.md'
      - '**.txt'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PR_NR: ${{ github.event.pull_request.number }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  linux:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      # Prepare environment
      - name: prepare environment
        run: |
          sudo timedatectl set-timezone Europe/Amsterdam
          if [ "${GITHUB_EVENT_NAME}" == 'pull_request' ]; then
            echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
            echo "PRNUMBER=$(echo ${PR_NR})" >> $GITHUB_ENV
            echo "Domoticz PR check for PR ${PR_NR} from branch ${GITHUB_HEAD_REF}"
          else
            echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
            echo "PRNUMBER=$(echo ${GITHUB_SHA})" >> $GITHUB_ENV
          fi

      # install dependencies
      - name: dependencies
        run: |
          echo 'APT::Get::Always-Include-Phased-Updates "false";' | sudo tee /etc/apt/apt.conf.d/99-phased-updates
          sudo apt-mark hold grub-efi-amd64-signed
          sudo apt-get update --fix-missing
          sudo apt-get install cmake make gcc g++ libssl-dev git libcurl4-gnutls-dev libusb-dev libmosquitto-dev python3-dev zlib1g-dev liblua5.3-dev uthash-dev libsqlite3-dev
          sudo apt-get install libboost-chrono-dev libboost-system-dev libboost-thread-dev
          sudo apt-get install python3-pytest python3-pytest-bdd

      # Domoticz
      - name: build domoticz
        run: |
          cd $GITHUB_WORKSPACE
          cmake -DCMAKE_BUILD_TYPE=Release -DUSE_OPENZWAVE=NO CMakeLists.txt
          make -j$(nproc)

      # Packaging
      - name: package domoticz
        run: |
          cd $GITHUB_WORKSPACE
          mkdir package
          tar czf package/domoticz_linux_x86_64.tgz domoticz History.txt License.txt domoticz.sh server_cert.pem updatebeta updaterelease www/ scripts/ Config/ dzVents/
          shasum -a 256 package/domoticz_linux_x86_64.tgz > package/domoticz_linux_x86_64.tgz.sha256sum
          cp appversion.h.txt package/version_linux_x86_64.h
          cp History.txt package/history_linux_x86_64.txt

      # Artifact upload
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: domoticz_linux_x86_64-${{ github.event.pull_request.number }}-${{ github.run_number }}
          path: package/domoticz_linux_x86_64.tgz
          retention-days: 7