name: Windows Development Build

concurrency:
  group: windows-dev-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - development
    paths-ignore:
      - 'tools/**'
      - '**.md'
      - '**.txt'

jobs:
  build:
    runs-on: windows-2022

    if: github.repository == 'domoticz/domoticz'

    env:
      CONFIGURATION: Release
      PLATFORM: x86

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Install InnoSetup
        shell: powershell
        run: nuget install Tools.InnoSetup

      - name: Download WindowsLibraries
        shell: powershell
        run: |
          cd msbuild
          Invoke-WebRequest `
            -Uri "https://raw.githubusercontent.com/domoticz/win32-libraries/master/WindowsLibraries.7z" `
            -OutFile "WindowsLibraries.7z"
          7z x WindowsLibraries.7z | Out-Null
          cd ..

      - name: Build Domoticz
        shell: cmd
        run: msbuild msbuild\domoticz.sln /m /p:Configuration=${{ env.CONFIGURATION }} /p:Platform=${{ env.PLATFORM }} /verbosity:minimal

      - name: Create installer and package
        shell: cmd
        run: |
          copy appversion.h version_windows_x86.h
          copy History.txt history_windows_x86.txt
          move Tools.InnoSetup.* Tools.InnoSetup
          Tools.InnoSetup\tools\ISCC msbuild\WindowsInstaller\DomoticzSetup.iss
          msbuild msbuild\package.proj

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-x86
          path: |
            domoticz_windows_x86.zip
            version_windows_x86.h
            history_windows_x86.txt
            History.txt

      - name: Deploy to SFTP
        if: github.ref == 'refs/heads/development'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: |
            domoticz_windows_x86.zip
            version_windows_x86.h
            history_windows_x86.txt
            History.txt
          target: beta
