---
apiVersion: v1
kind: Service
metadata:
  name: svc-domoticz-{{ .Values.general.name }}
  labels:
    app: domoticz
    environment: {{ .Values.general.environment }}
    client: {{ .Values.general.name }}
  annotations:
    prometheus.io/scrape: 'true'
    filter.by.port.name: 'true'
    app: domoticz
    app.business.client: {{ .Values.general.name }}
    app.owner: 'Domoticz'
    app.helm-chart: 'https://hub.docker.com/repository/docker/jpradoar/'
    app.imageregistry: 'https://hub.docker.com/r/domoticz/domoticz/' 
spec:
  selector:
    app: domoticz
    environment: {{ .Values.general.environment }}
    client: {{ .Values.general.name }}    
  ports:
    - name: http
      protocol: TCP     
      port: 8080        
      targetPort: 8080
    - name: https
      protocol: TCP     
      port: 8443        
      targetPort: 443      